# Generated by Django 3.2.9 on 2022-05-14 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='projectmanager',
            name='is_verified',
        ),
    ]
