# Generated by Django 3.2.9 on 2022-05-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeApi', '0002_auto_20220514_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to='app_homeApi.company'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_manager', to='app_homeApi.company'),
        ),
    ]
