# Generated by Django 3.2.9 on 2022-05-31 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeApi', '0008_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
