# Generated by Django 3.2.9 on 2022-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeApi', '0010_alter_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='topic',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
