# Generated by Django 3.2.9 on 2022-02-04 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=25, unique=True)),
                ('company_profile', models.EmailField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('designation', models.BooleanField(default=False)),
                ('skills', models.CharField(db_index=True, max_length=25, unique=True)),
                ('experience', models.IntegerField(default=0)),
                ('vacancy', models.IntegerField(default=0)),
                ('job_description', models.CharField(db_index=True, max_length=25, unique=True)),
                ('place', models.CharField(db_index=True, max_length=25, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('job_type', models.CharField(db_index=True, max_length=25, unique=True)),
                ('educational_qualification', models.CharField(db_index=True, max_length=25, unique=True)),
                ('contact_number', models.IntegerField(default=0)),
                ('contact_email', models.EmailField(db_index=True, max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
                ('company', models.CharField(db_index=True, max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='appJobAPI.postedjob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
