# Generated by Django 3.2.9 on 2022-05-14 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_homeApi', '0003_auto_20220514_2244'),
        ('appJobAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appliedjob',
            old_name='created_at',
            new_name='applied_at',
        ),
        migrations.RemoveField(
            model_name='appliedjob',
            name='name',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='company_profile',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='educational_qualification',
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='appointed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='educational_qualification1',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='educational_qualification2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='educational_qualification3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='maximum_age',
            field=models.IntegerField(blank=True, default=60, null=True),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='minimum_age',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_jobs', to='app_homeApi.company'),
        ),
        migrations.AlterField(
            model_name='appliedjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='company_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posted_job', to='app_homeApi.company'),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='contact_email',
            field=models.EmailField(max_length=30),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='designation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='job_description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='job_type',
            field=models.CharField(blank=True, choices=[('OFF_LINE', 'Off-line'), ('REMOTE', 'Remote'), ('PROJECT', 'Project')], default='PROJECT', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='skills',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='postedjob',
            name='vacancy',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
