# Generated by Django 3.2.9 on 2022-05-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0002_auto_20220514_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postedjob',
            old_name='educational_qualification1',
            new_name='educational_qualification',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='educational_qualification2',
        ),
        migrations.RemoveField(
            model_name='postedjob',
            name='educational_qualification3',
        ),
    ]
