# Generated by Django 3.2.9 on 2022-05-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0003_auto_20220515_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='document_image1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='postedjob',
            name='document_image2',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
