# Generated by Django 3.2.9 on 2022-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0004_auto_20220515_0234'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='job_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
