# Generated by Django 3.2.9 on 2022-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0005_postedjob_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='salary2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
