# Generated by Django 3.2.9 on 2022-05-15 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0006_postedjob_salary2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliedjob',
            name='company',
        ),
    ]
