# Generated by Django 3.2.9 on 2022-05-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0007_remove_appliedjob_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='email',
            field=models.EmailField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='appliedjob',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
