# Generated by Django 3.2.9 on 2022-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0008_auto_20220515_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjob',
            name='cv',
            field=models.FileField(default=1, upload_to='cv/'),
            preserve_default=False,
        ),
    ]
