# Generated by Django 3.2.9 on 2022-05-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0009_alter_appliedjob_cv'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliedjob',
            name='resigned',
            field=models.BooleanField(default=False),
        ),
    ]
