# Generated by Django 3.2.9 on 2022-06-01 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appJobAPI', '0010_appliedjob_resigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedjob',
            name='apply_last_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
